run:
  issues-exit-code: 1
  tests: false

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable:
      - nilness
      - shadow
  revive:
    confidence: 0
    ignore-generated-header: true
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - unused
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - goimports

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # Skip deprecation warnings.
    - SA1019
    # for "public interface + private struct implementation" cases only!
    # can be removed in the development phase
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    - should have a package comment, unless it's in another file for this package
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    - should check returned error before deferring
